package com.adproject.community.application;
import com.adproject.common.api.ApiException; import com.adproject.common.security.AuthenticatedUser; import com.adproject.common.time.DatabaseTimePrecision;
import com.adproject.community.api.CommunityDirectDtos.Conversation; import com.adproject.community.api.CommunityDirectDtos.ConversationResponse; import com.adproject.community.api.CommunityDirectDtos.Message; import com.adproject.community.api.CommunityDirectDtos.MessageListResponse; import com.adproject.community.api.CommunityDirectDtos.MessageResponse; import com.adproject.community.api.CommunityDirectDtos.SendMessageRequest; import com.adproject.community.api.CommunityDtos.CommunityAuthor; import com.adproject.community.api.CommunityDtos.PageMeta; import com.adproject.community.infrastructure.*;
import com.adproject.company.infrastructure.*; import com.adproject.user.domain.UserRole; import com.adproject.user.infrastructure.*;
import java.time.Clock; import java.util.*; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class CommunityDirectMessageService {
 private final CommunityPostRepository posts; private final CommunityDirectConversationRepository conversations; private final CommunityDirectMessageRepository messages;
 private final UserRepository users; private final CompanyMemberRepository members; private final CompanyRepository companies; private final Clock clock;
 public CommunityDirectMessageService(CommunityPostRepository posts,CommunityDirectConversationRepository conversations,CommunityDirectMessageRepository messages,UserRepository users,CompanyMemberRepository members,CompanyRepository companies,Clock clock){this.posts=posts;this.conversations=conversations;this.messages=messages;this.users=users;this.members=members;this.companies=companies;this.clock=clock;}
 @Transactional public ConversationResponse start(AuthenticatedUser principal,String postId){requireRole(principal);var post=posts.findById(postId).orElseThrow(this::notFound);String me=principal.userId(),author=post.getAuthorId();if(me.equals(author))throw new ApiException(HttpStatus.CONFLICT,"CANNOT_MESSAGE_SELF","You cannot start a direct conversation with yourself");String a=me.compareTo(author)<0?me:author,b=me.compareTo(author)<0?author:me;var now=DatabaseTimePrecision.micros(clock.instant());var conversation=conversations.findByParticipantAIdAndParticipantBId(a,b).orElseGet(()->conversations.save(new CommunityDirectConversationEntity(UUID.randomUUID().toString(),a,b,now)));return new ConversationResponse(dto(conversation,me));}
 @Transactional(readOnly=true) public ConversationResponse detail(AuthenticatedUser principal,String id){return new ConversationResponse(dto(requireConversation(principal,id),principal.userId()));}
 @Transactional(readOnly=true) public MessageListResponse messages(AuthenticatedUser principal,String id,int page,int pageSize){var conversation=requireConversation(principal,id);var result=messages.findByConversationId(conversation.getId(),PageRequest.of(page-1,pageSize,Sort.by(Sort.Order.asc("sentAt"),Sort.Order.asc("id"))));return new MessageListResponse(result.getContent().stream().map(this::message).toList(),new PageMeta(page,pageSize,result.getTotalElements(),result.hasNext()));}
 @Transactional public MessageResponse send(AuthenticatedUser principal,String id,SendMessageRequest request){var conversation=requireConversation(principal,id);String body=CommunityTextNormalizer.normalize(request==null?null:request.body(),"body",2000);var now=DatabaseTimePrecision.micros(clock.instant());var value=messages.save(new CommunityDirectMessageEntity(UUID.randomUUID().toString(),id,principal.userId(),body,now));conversation.touch(now);return new MessageResponse(message(value));}
 private CommunityDirectConversationEntity requireConversation(AuthenticatedUser principal,String id){requireRole(principal);return conversations.findById(id).filter(value->value.includes(principal.userId())).orElseThrow(this::notFound);}
 private Conversation dto(CommunityDirectConversationEntity value,String viewer){var other=users.findById(value.other(viewer)).orElseThrow();return new Conversation(value.getId(),author(other),value.getCreatedAt(),value.getUpdatedAt());}
 private CommunityAuthor author(UserEntity user){String company=null;if(user.getRole()==UserRole.RECRUITER)company=members.findByUserId(user.getId()).flatMap(m->companies.findById(m.getCompanyId())).map(CompanyEntity::getName).orElse(null);return new CommunityAuthor(user.getId(),user.getFullName(),user.getAvatarUrl(),user.getRole().name(),company);}
 private Message message(CommunityDirectMessageEntity value){return new Message(value.getId(),value.getConversationId(),value.getSenderId(),value.getBody(),value.getSentAt());}
 private ApiException notFound(){return new ApiException(HttpStatus.NOT_FOUND,"NOT_FOUND","Community direct conversation not found");}
 private static void requireRole(AuthenticatedUser p){if(p==null||(p.role()!=UserRole.CANDIDATE&&p.role()!=UserRole.RECRUITER))throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN","Insufficient permission");}
}
