import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {recruiterRepository as repo} from './repository';
import type {JobDraft} from '../models/recruiter';
import type {ListApplicationsParams,ListJobsParams,RecruiterJobStatusTarget,RecruiterTransitionStatus} from './recruiterRepository';
export const keys={me:['me'] as const,dashboard:['dashboard'] as const,jobs:(params:ListJobsParams={})=>['jobs',params] as const,job:(id:string)=>['job',id] as const,applications:(params:ListApplicationsParams={})=>['applications',params] as const,application:(id:string)=>['application',id] as const,conversations:['conversations'] as const,conversation:(id:string)=>['conversation',id] as const};
export const useMe=()=>useQuery({queryKey:keys.me,queryFn:()=>repo.getMe()});
export const useDashboard=()=>useQuery({queryKey:keys.dashboard,queryFn:()=>repo.getDashboard()});
export const useJobs=(params:ListJobsParams={})=>useQuery({queryKey:keys.jobs(params),queryFn:()=>repo.listJobs(params)});
export const useJob=(id:string)=>useQuery({queryKey:keys.job(id),queryFn:()=>repo.getJob(id),enabled:!!id});
export const useCreateJob=()=>{const qc=useQueryClient();return useMutation({mutationFn:(input:JobDraft)=>repo.createJob(input),onSuccess:job=>{qc.invalidateQueries({queryKey:['jobs']});qc.setQueryData(keys.job(job.jobId),job);}});};
export const useUpdateJob=()=>{const qc=useQueryClient();return useMutation({mutationFn:({jobId,input,expectedVersion}:{jobId:string;input:JobDraft;expectedVersion:number})=>repo.updateJob(jobId,input,expectedVersion),onSuccess:job=>{qc.setQueryData(keys.job(job.jobId),job);qc.invalidateQueries({queryKey:['jobs']});}});};
export const usePublishJob=()=>{const qc=useQueryClient();return useMutation({mutationFn:({jobId,expectedVersion}:{jobId:string;expectedVersion:number})=>repo.publishJob(jobId,expectedVersion),onSuccess:job=>{qc.setQueryData(keys.job(job.jobId),job);qc.invalidateQueries({queryKey:['jobs']});}});};
export const useChangeJobStatus=()=>{const qc=useQueryClient();return useMutation({mutationFn:({jobId,status,reason,expectedVersion}:{jobId:string;status:RecruiterJobStatusTarget;reason:string;expectedVersion:number})=>repo.changeJobStatus(jobId,status,reason,expectedVersion),onSuccess:job=>{qc.setQueryData(keys.job(job.jobId),job);qc.invalidateQueries({queryKey:['jobs']});}});};
export const useApplications=(params:ListApplicationsParams={})=>useQuery({queryKey:keys.applications(params),queryFn:()=>repo.listApplications(params)});
export const useApplication=(id:string)=>useQuery({queryKey:keys.application(id),queryFn:()=>repo.getApplication(id),enabled:!!id});
export const useUpdateApplication=()=>{const qc=useQueryClient();return useMutation({mutationFn:({id,status,reason,expectedVersion}:{id:string;status:RecruiterTransitionStatus;reason:string;expectedVersion:number})=>repo.updateApplicationStatus(id,status,reason,expectedVersion),onSuccess:(a)=>{qc.invalidateQueries({queryKey:['applications']});qc.setQueryData(keys.application(a.applicationId),a);}});};
export const useConversations=()=>useQuery({queryKey:keys.conversations,queryFn:()=>repo.listConversations()});
export const useConversation=(id:string)=>useQuery({queryKey:keys.conversation(id),queryFn:()=>repo.getConversation(id),enabled:!!id});
export const useSendMessage=()=>{const qc=useQueryClient();return useMutation({mutationFn:({id,body}:{id:string;body:string})=>repo.sendMessage(id,body),onSuccess:r=>{qc.setQueryData(keys.conversation(r.conversation.conversationId),r.conversation);qc.invalidateQueries({queryKey:keys.conversations});}});};
