import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useJobs, useSetJobStatus} from '../api/queries';
import {EmptyState, ErrorState, LoadingState} from '../components/AsyncState';
import {PageHeader} from '../components/PageHeader';
import {StatusBadge} from '../components/StatusBadge';

export function JobsPage() {
  const nav = useNavigate(); const query = useJobs(); const mutation = useSetJobStatus();
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL');
  if (query.isLoading) return <LoadingState label="Loading job postings…"/>;
  if (query.isError || !query.data) return <ErrorState onRetry={() => query.refetch()}/>;
  const items = query.data.filter(job => (status === 'ALL' || job.status === status) && job.title.toLowerCase().includes(search.toLowerCase()));
  const counts = {active: query.data.filter(job => job.status === 'ACTIVE').length, draft: query.data.filter(job => job.status === 'DRAFT').length, paused: query.data.filter(job => job.status === 'PAUSED').length, total: query.data.length};
  return <><PageHeader title="Open Roles" subtitle="Manage active, draft, and paused job postings." actions={<div className="actions"><button className="button secondary">Archived roles</button><button className="button primary" onClick={() => nav('/recruiter/jobs/new')}>Create job posting</button></div>}/><section className="metric-grid four">{[['Open roles', counts.active], ['Draft', counts.draft], ['Paused', counts.paused], ['Total postings', counts.total]].map(([label, value]) => <div className="metric-card" key={label}><strong>{value}</strong><b>{label}</b></div>)}</section><section className="table-panel"><div className="table-toolbar"><div className="grow"><h2>All job postings</h2><small>{query.data.length} postings across all statuses</small></div><input value={search} onChange={event => setSearch(event.target.value)} placeholder="⌕ Search job by title"/><select value={status} onChange={event => setStatus(event.target.value)}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="DRAFT">Draft</option><option value="PAUSED">Paused</option><option value="CLOSED">Closed</option></select></div>{items.length === 0 ? <EmptyState title="No job postings found" description="Try a different search or create a new role."/> : <div className="data-table jobs-table"><div className="table-head"><span>Job title</span><span>Employment type</span><span>Status</span><span>Published</span><span>Applicants</span><span>Owner</span><span/></div>{items.map(job => <div className="table-row" key={job.jobId}><span className="person"><i className="avatar">{job.title.split(' ').map(word => word[0]).slice(0, 2).join('')}</i><span><b>{job.title}</b><small>{job.company.name}</small></span></span><span><b>{job.employmentType.replace('_', ' ')}</b><small>{job.location} · {job.workplaceType}</small></span><StatusBadge status={job.status}/><span>{job.publishedAt ? new Date(job.publishedAt).toLocaleDateString() : 'Not published'}</span><span className="pill">{job.applicantCount} applicants</span><span>{job.owner?.fullName ?? 'Unassigned'}</span><span className="row-actions"><button className="button tiny secondary" onClick={() => nav(`/recruiter/jobs/${job.jobId}/edit`)}>Edit role</button><button className="text-button" disabled={mutation.isPending || job.status === 'CLOSED'} onClick={() => mutation.mutate({id: job.jobId, status: job.status === 'ACTIVE' ? 'PAUSED' : 'ACTIVE'})}>{job.status === 'ACTIVE' ? 'Pause' : 'Activate'}</button></span></div>)}</div>}<footer className="pagination"><span>Showing 1–{items.length} of {items.length} job postings</span></footer></section></>;
}
