import {useEffect, useState, type FormEvent} from 'react';
import {useNavigate, useParams} from 'react-router-dom';
import {useConversation, useConversations, useSendMessage} from '../api/queries';
import {EmptyState, ErrorState, LoadingState} from '../components/AsyncState';
import {PageHeader} from '../components/PageHeader';

export function MessagesPage() {
  const {conversationId} = useParams(); const nav = useNavigate(); const list = useConversations();
  const activeId = conversationId ?? list.data?.[0]?.conversationId ?? '';
  const detail = useConversation(activeId); const send = useSendMessage(); const [body, setBody] = useState('');
  useEffect(() => {if (!conversationId && list.data?.[0]) nav(`/recruiter/messages/${list.data[0].conversationId}`, {replace: true});}, [conversationId, list.data, nav]);
  if (list.isLoading) return <LoadingState label="Loading conversations…"/>;
  if (list.isError || !list.data) return <ErrorState onRetry={() => list.refetch()}/>;
  const submit = (event: FormEvent) => {event.preventDefault(); if (body.trim()) send.mutate({id: activeId, body: body.trim()}, {onSuccess: () => setBody('')});};
  return <><PageHeader title="Messages" subtitle="Chat with candidates and keep hiring conversations in one place."/><section className="messages-panel"><aside className="conversation-list"><div className="section-title"><div><h2>Conversations</h2><small>{list.data.length} candidates</small></div></div><input placeholder="Search candidate"/>{list.data.length === 0 ? <EmptyState title="No conversations"/> : list.data.map(conversation => <button className={conversation.conversationId === activeId ? 'selected' : ''} key={conversation.conversationId} onClick={() => nav(`/recruiter/messages/${conversation.conversationId}`)}><span className="avatar large">{conversation.participant.fullName[0]}</span><span className="grow"><b>{conversation.participant.fullName}</b><small>{conversation.jobTitle} · {conversation.lastMessage?.body}</small></span>{conversation.unreadCount > 0 && <span className="unread">{conversation.unreadCount}</span>}</button>)}</aside><article className="chat-view">{detail.isLoading ? <LoadingState/> : detail.data ? <><header><span className="avatar">{detail.data.participant.fullName[0]}</span><span className="grow"><b>{detail.data.participant.fullName}</b><small>Applied to {detail.data.jobTitle} · {detail.data.matchScore ?? 0}% ML match</small></span><button className="button secondary" onClick={() => nav(`/recruiter/applications/${detail.data!.applicationId}`)}>View application</button></header><div className="messages">{detail.data.messages.map(message => <div key={message.messageId} className={`message ${message.senderType.toLowerCase()}`}><span>{message.body}</span>{message.senderType !== 'SYSTEM' && <small>{new Date(message.sentAt).toLocaleTimeString([], {hour: '2-digit', minute: '2-digit'})}</small>}</div>)}</div><form className="message-composer" onSubmit={submit}><button type="button" className="circle-button">+</button><input value={body} onChange={event => setBody(event.target.value)} placeholder="Write a message…"/><button className="button primary" disabled={!body.trim() || send.isPending}>{send.isPending ? 'Sending…' : 'Send'}</button></form></> : <EmptyState title="Select a conversation"/>}</article></section></>;
}
