package com.adproject.resume.application;
import com.adproject.common.api.ApiException; import com.adproject.common.security.AuthenticatedUser; import com.adproject.common.time.DatabaseTimePrecision; import com.adproject.resume.api.ResumeDtos.Experience; import com.adproject.resume.api.ResumeDtos.Resume; import com.adproject.resume.api.ResumeDtos.ResumeResponse; import com.adproject.resume.api.ResumeDtos.SaveResumeRequest; import com.adproject.resume.infrastructure.*; import com.adproject.user.domain.UserRole; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import java.time.Clock; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class CandidateResumeService {
 private static final TypeReference<List<Experience>> LIST=new TypeReference<>(){}; private final ResumeRepository repository; private final ObjectMapper mapper; private final Clock clock;
 public CandidateResumeService(ResumeRepository repository,ObjectMapper mapper,Clock clock){this.repository=repository;this.mapper=mapper;this.clock=clock;}
 @Transactional(readOnly=true) public ResumeResponse get(AuthenticatedUser p){requireCandidate(p);return response(repository.findByCandidateId(p.userId()).orElseThrow(CandidateResumeService::notFound));}
 @Transactional public ResumeResponse save(AuthenticatedUser p,SaveResumeRequest r){requireCandidate(p);var existing=repository.findByCandidateIdForUpdate(p.userId()).orElse(null);var now=DatabaseTimePrecision.micros(clock.instant());String json=write(r.experiences()); if(existing==null){if(r.expectedVersion()!=0)throw version();existing=repository.save(new ResumeEntity(UUID.randomUUID().toString(),p.userId(),r.fullName(),r.age(),r.location(),r.headline(),r.summary(),json,1,now,now));}else{if(existing.getVersion()!=r.expectedVersion())throw version();existing.replace(r.fullName(),r.age(),r.location(),r.headline(),r.summary(),json,now);}repository.flush();return response(existing);}
 private ResumeResponse response(ResumeEntity e){return new ResumeResponse(new Resume(e.getId(),e.getFullName(),e.getAge(),e.getLocation(),e.getHeadline(),e.getSummary(),read(e.getExperiencesJson()),e.getVersion(),e.getCreatedAt(),e.getUpdatedAt()));}
 private String write(List<Experience> v){try{return mapper.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}} private List<Experience> read(String v){try{return mapper.readValue(v,LIST);}catch(Exception e){throw new IllegalStateException(e);}}
 private static void requireCandidate(AuthenticatedUser p){if(p==null||p.role()!=UserRole.CANDIDATE)throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN","Insufficient permission");} private static ApiException notFound(){return new ApiException(HttpStatus.NOT_FOUND,"NOT_FOUND","Resume not found");} private static ApiException version(){return new ApiException(HttpStatus.CONFLICT,"VERSION_CONFLICT","The resume has changed");}
}
